#ifndef _VFSERRORCODES_H_
#define _VFSERRORCODES_H_

#define VFS_ERROR_TYPE_BASE(code)		((code))
#define VFS_ERROR_TYPE_INTERNAL(code)	((code) | (1 << 31))


#define	VFS_OK								(VFS_ERROR_TYPE_BASE(0x00))
#define VFS_FAILED_TO_CREATE_FILE			(VFS_ERROR_TYPE_BASE(0x01))
#define VFS_FAILED_TO_OPEN_FILE				(VFS_ERROR_TYPE_BASE(0x02))
#define VFS_READ_NO_CLUSTERS				(VFS_ERROR_TYPE_BASE(0x03))
#define VFS_CANNOT_OPEN_CHAIN				(VFS_ERROR_TYPE_BASE(0x04))
#define VFS_OUT_OF_BOUNDS					(VFS_ERROR_TYPE_BASE(0x05))
#define VFS_CANNOT_ALLOCATE					(VFS_ERROR_TYPE_BASE(0x06))
#define VFS_CANNOT_RESIZE					(VFS_ERROR_TYPE_BASE(0x07))
#define VFS_CANNOT_CREATE_CACHE				(VFS_ERROR_TYPE_BASE(0x08))
#define VFS_INVALID_VERSION					(VFS_ERROR_TYPE_BASE(0x09))
#define VFS_INVALID_FOURC_CC				(VFS_ERROR_TYPE_BASE(0x0A))
#define VFS_INVALID_USER_VERSION			(VFS_ERROR_TYPE_BASE(0x0B))
#define VFS_READ_ONLY						(VFS_ERROR_TYPE_BASE(0x0C))
#define VFS_PARSING_FAILURE					(VFS_ERROR_TYPE_BASE(0x0D))
#define VFS_CANNOT_CREATE_FILE				(VFS_ERROR_TYPE_BASE(0x0E))
#define VFS_CANNOT_OPEN_FILE				(VFS_ERROR_TYPE_BASE(0x0F))
#define VFS_WRITE_LOCKED_FILE				(VFS_ERROR_TYPE_BASE(0x10))
#define VFS_READ_LOCKED_FILE				(VFS_ERROR_TYPE_BASE(0x11))
#define VFS_INVALID_OPEN_MODE				(VFS_ERROR_TYPE_BASE(0x12))
#define VFS_FILE_IN_USE						(VFS_ERROR_TYPE_BASE(0x13))
#define VFS_FILE_EXISTS						(VFS_ERROR_TYPE_BASE(0x14))
#define VFS_FAILED_TO_OPEN_CLUSTER_FILE		(VFS_ERROR_TYPE_BASE(0x15))
#define VFS_FAILED_TO_CREATE_CLUSTER_FILE	(VFS_ERROR_TYPE_BASE(0x16))
#define VFS_CANNOT_FIND_ENTRY				(VFS_ERROR_TYPE_BASE(0x17))
#define VFS_ERROR_NOT_A_FILE				(VFS_ERROR_TYPE_BASE(0x18))
#define VFS_ERROR_NOT_A_DIRECTORY			(VFS_ERROR_TYPE_BASE(0x19))
#define VFS_ERROR_INVALID_UID				(VFS_ERROR_TYPE_BASE(0x1A))
#define VFS_CANNOT_FIND_FILE				(VFS_ERROR_TYPE_BASE(0x1B))
#define VFS_CANNOT_FIND_DIRECTORY			(VFS_ERROR_TYPE_BASE(0x1C))
#define VFS_DELETION_FAILED					(VFS_ERROR_TYPE_BASE(0x1D))
#define VFS_NOT_IMPLEMENTED					(VFS_ERROR_TYPE_BASE(0x1E))



#define VFS_SUCCESS(retcode)	((retcode) == VFS_OK)
#define VFS_FAIL(retcode)		((retcode) != VFS_OK)






#endif //_VFSERRORCODES_H_
