import io

HDR = """# TT 4.8.4 vs OpenW3D — class declaration deltas

Phase 1 deliverable for roadmap Section 7. Covers the 22 public engine classes the
roadmap names by hand. Generated by comparing the two declarations directly;
see the caveats at the bottom before relying on a number.

Baselines: OpenW3D `b970f592`, TT donor `tt_4.8.4/` (the `shaders/` tree is excluded
per directive 0.6 and was not searched).

Methods are compared on **name + arity**, so an overload set collapses to one entry
per distinct arity and parameter-name/spelling differences do not create false
deltas. Data members are compared on name.

---

## Summary

| Class | TT | OpenW3D | TT methods | OW methods | TT-only methods | TT-only fields | Disposition |
| --- | --- | --- | --- | --- | --- | --- | --- |
"""

FOOT = """
---

## Dispositions

**MERGE (14).** The class exists on both sides with an identical base list. TT's
version is a superset; Phase 2 folds the TT additions into the canonical OpenW3D
class and deletes TT's copy. Classes with a non-zero delta, largest first (the
naming-fix case is included because it merges the same way once renamed):

__MERGE_TABLE__

`CullSystemClass`, `DefinitionMgrClass` and `DynamicShadowManagerClass` show no
declaration-level delta at all — TT carries them only so its own translation units
compile against the closed binary. They need no Phase 2 work beyond deletion.

**NAMING FIX (1).** `SamSiteGameObj` (TT) is `SAMSiteGameObj` (OpenW3D,
`Code/Combat/samsite.h:73`). Same class, different capitalisation. Every TT
reference must be renamed on merge rather than creating a second type. This is the
one case where an exact-match search reports a false "absent".

**NEW (7).** No OpenW3D counterpart exists; these arrive as new source files:
`AirFactoryGameObj`, `NavalFactoryGameObj`, `ConstructionYardGameObj`,
`SuperweaponGameObj`, `HUDSurfaceClass`, `ScriptedDialogClass`,
`ExtendedNetworkObject`.

Four of the seven are building subclasses that extend `BuildingGameObj`, which is
why `BuildingGameObj` grows four new `As_*` downcasts. They also explain
`BuildingGameObj`'s other additions: `Find_MCT`, `Get_Bounds`, `Cast_Ray`,
`Building_In_Range` and `Find_Closest_Poly*` are the geometry queries those
subclasses need. That cluster is directly relevant to P33/P37/P38 — automatic
PCT/MCT placement from W3D semantic nodes and ghost-placement validation both need
exactly these primitives.

`HUDSurfaceClass` and `ScriptedDialogClass` are a server-driven UI facility with no
stock equivalent: both carry `Get_Client_ID` / `Is_Dirty` / `Set_Dirty` and an
element or control collection. `ExtendedNetworkObject` adds one method,
`setDirtyBitsForClient`, on the same theme — per-client dirty tracking. Phase 5
should treat the three as one feature, not three classes.

---

## Caveats

- This is a **declaration-level** diff. A method present in both trees with the same
  name and arity is reported as matching even if TT changed its behaviour, its
  parameter types, or its return type. Behavioural deltas live in the hook data
  (`TTHookSites.tsv`), not here.
- Bodies defined inline in the header are counted as declarations, which is correct
  for this purpose but means "methods" is not a vtable size.
- TT declares many of these classes purely to describe the stock binary's layout, so
  a small delta usually means "TT needed the type", not "TT changed the type".
"""


def emit(rows, detail):
    out = [HDR]
    for r in rows:
        out.append('| `%s` | %s | %s | %s | %s | %s | %s | %s |\n' % r)
    out.append('\n---\n\n## Per-class detail\n\n')
    out.append(''.join(detail))
    mt = ['| Class | TT-only methods | TT-only fields |', '| --- | --- | --- |']
    mg = [r for r in rows if r[7] != '**NEW**']
    mg.sort(key=lambda r: (r[5] + r[6]), reverse=True)
    for r in mg:
        if r[5] or r[6]:
            mt.append('| `%s` | %d | %d |' % (r[0], r[5], r[6]))
    out.append(FOOT.replace('__MERGE_TABLE__', chr(10).join(mt)))
    io.open('docs/tt484/TTClassDeltas.md', 'w', encoding='utf-8',
            newline='\n').write(''.join(out))
