#ifndef TT_INCLUDE__INPUT_H
#define TT_INCLUDE__INPUT_H
#include "engine_string.h"
#include "engine_io.h"
typedef enum {

	INPUT_FUNCTION_MOVE_FORWARD,
	INPUT_FUNCTION_MOVE_BACKWARD,
	INPUT_FUNCTION_MOVE_LEFT,
	INPUT_FUNCTION_MOVE_RIGHT,
	INPUT_FUNCTION_MOVE_UP,				// helicopters and orcas
	INPUT_FUNCTION_MOVE_DOWN,

	INPUT_FUNCTION_WALK_MODE,

	INPUT_FUNCTION_TURN_LEFT,
	INPUT_FUNCTION_TURN_RIGHT,

	INPUT_FUNCTION_VEHICLE_TURN_LEFT,
	INPUT_FUNCTION_VEHICLE_TURN_RIGHT,
	INPUT_FUNCTION_VEHICLE_TOGGLE_GUNNER,

	INPUT_FUNCTION_WEAPON_UP,
	INPUT_FUNCTION_WEAPON_DOWN,
	INPUT_FUNCTION_WEAPON_LEFT,
	INPUT_FUNCTION_WEAPON_RIGHT,
	INPUT_FUNCTION_WEAPON_RESET,

	INPUT_FUNCTION_ZOOM_IN,
	INPUT_FUNCTION_ZOOM_OUT,

	INPUT_FUNCTION_ACTION,				// Was LADDER
	INPUT_FUNCTION_JUMP,
	INPUT_FUNCTION_CROUCH,

	INPUT_FUNCTION_DIVE_FORWARD,
	INPUT_FUNCTION_DIVE_BACKWARD,
	INPUT_FUNCTION_DIVE_LEFT,
	INPUT_FUNCTION_DIVE_RIGHT,

	INPUT_FUNCTION_TURN_AROUND,
	INPUT_FUNCTION_DROP_FLAG,

	INPUT_FUNCTION_NEXT_WEAPON,
	INPUT_FUNCTION_PREV_WEAPON,
	INPUT_FUNCTION_FIRE_WEAPON_PRIMARY,
	INPUT_FUNCTION_FIRE_WEAPON_SECONDARY,
	INPUT_FUNCTION_USE_WEAPON,
	INPUT_FUNCTION_RELOAD_WEAPON,

	INPUT_FUNCTION_SELECT_NO_WEAPON,
	INPUT_FUNCTION_SELECT_WEAPON_0,
	INPUT_FUNCTION_SELECT_WEAPON_1,
	INPUT_FUNCTION_SELECT_WEAPON_2,
	INPUT_FUNCTION_SELECT_WEAPON_3,
	INPUT_FUNCTION_SELECT_WEAPON_4,
	INPUT_FUNCTION_SELECT_WEAPON_5,
	INPUT_FUNCTION_SELECT_WEAPON_6,
	INPUT_FUNCTION_SELECT_WEAPON_7,
	INPUT_FUNCTION_SELECT_WEAPON_8,
	INPUT_FUNCTION_SELECT_WEAPON_9,

	INPUT_FUNCTION_CYCLE_POG,

//	INPUT_FUNCTION_HUD_ZOOM_RADAR_IN,
//	INPUT_FUNCTION_HUD_ZOOM_RADAR_OUT,

	INPUT_FUNCTION_PANIC,
	INPUT_FUNCTION_CURSOR_TARGETING,
	INPUT_FUNCTION_FIRST_PERSON_TOGGLE,
	INPUT_FUNCTION_SUICIDE,

	INPUT_FUNCTION_VERBOSE_HELP,

	INPUT_FUNCTION_BEGIN_PUBLIC_MESSAGE,
	INPUT_FUNCTION_BEGIN_TEAM_MESSAGE,
	INPUT_FUNCTION_BEGIN_PRIVATE_MESSAGE,
	INPUT_FUNCTION_BEGIN_CONSOLE,

	INPUT_FUNCTION_HELP_SCREEN,

	INPUT_FUNCTION_EVA_OBJECTIVES_SCREEN,
	INPUT_FUNCTION_EVA_MAP_SCREEN,

	// DEBUGGING
	INPUT_FUNCTION_CAMERA_HEADING_LEFT,
	INPUT_FUNCTION_CAMERA_HEADING_RIGHT,

	INPUT_FUNCTION_CAMERA_TRANSTILT_INC,
	INPUT_FUNCTION_CAMERA_TRANSTILT_DEC,
	INPUT_FUNCTION_CAMERA_VIEWTILT_INC,
	INPUT_FUNCTION_CAMERA_VIEWTILT_DEC,
	INPUT_FUNCTION_CAMERA_DIST_INC,
	INPUT_FUNCTION_CAMERA_DIST_DEC,
	INPUT_FUNCTION_CAMERA_FOV_INC,
	INPUT_FUNCTION_CAMERA_FOV_DEC,
	INPUT_FUNCTION_CAMERA_HEIGHT_INC,
	INPUT_FUNCTION_CAMERA_HEIGHT_DEC,

	INPUT_FUNCTION_MENU_SERVERQUICKSTART,
   INPUT_FUNCTION_MENU_CLIENTQUICKSTART,
	INPUT_FUNCTION_MAKE_SCREEN_SHOT,
	INPUT_FUNCTION_TOGGLE_MOVIE_CAPTURE,
	//INPUT_FUNCTION_INCREMENT_ACTIVE_MESSAGE,
	//INPUT_FUNCTION_DECREMENT_ACTIVE_MESSAGE,
	//INPUT_FUNCTION_INCREMENT_DEBUG_SWITCH_1,
	//INPUT_FUNCTION_INCREMENT_DEBUG_SWITCH_2,
	INPUT_FUNCTION_DEBUG_SINGLE_STEP,
	INPUT_FUNCTION_DEBUG_SINGLE_STEP_STEP,
	INPUT_FUNCTION_DEBUG_RAPID_MOVE,
	INPUT_FUNCTION_DEBUG_GENERIC0,
	INPUT_FUNCTION_DEBUG_GENERIC1,
	INPUT_FUNCTION_DEBUG_FAR_CLIP_IN,
	INPUT_FUNCTION_DEBUG_FAR_CLIP_OUT,
   INPUT_FUNCTION_QUICK_FULL_EXIT,
	INPUT_FUNCTION_VIS_UPDATE,
//	INPUT_FUNCTION_TOGGLE_PERFORMANCE_SAMPLING,
	INPUT_FUNCTION_TOGGLE_SNAP_SHOT_MODE,
	INPUT_FUNCTION_SNAP_SHOT_ADVANCE,
	//INPUT_FUNCTION_DEBUG_OPTIONS_DIALOG,
	INPUT_FUNCTION_CNC,
	INPUT_FUNCTION_QUICKSAVE,

	// Menu
	INPUT_FUNCTION_MENU_TOGGLE,

	// In game EVA
	INPUT_FUNCTION_EVA_MISSION_OBJECTIVES_TOGGLE,

	INPUT_FUNCTION_RADIO_CMD_01,
	INPUT_FUNCTION_RADIO_CMD_02,
	INPUT_FUNCTION_RADIO_CMD_03,
	INPUT_FUNCTION_RADIO_CMD_04,
	INPUT_FUNCTION_RADIO_CMD_05,
	INPUT_FUNCTION_RADIO_CMD_06,
	INPUT_FUNCTION_RADIO_CMD_07,
	INPUT_FUNCTION_RADIO_CMD_08,
	INPUT_FUNCTION_RADIO_CMD_09,
	INPUT_FUNCTION_RADIO_CMD_10,

	INPUT_FUNCTION_RADIO_CMD_11,
	INPUT_FUNCTION_RADIO_CMD_12,
	INPUT_FUNCTION_RADIO_CMD_13,
	INPUT_FUNCTION_RADIO_CMD_14,
	INPUT_FUNCTION_RADIO_CMD_15,
	INPUT_FUNCTION_RADIO_CMD_16,
	INPUT_FUNCTION_RADIO_CMD_17,
	INPUT_FUNCTION_RADIO_CMD_18,
	INPUT_FUNCTION_RADIO_CMD_19,
	INPUT_FUNCTION_RADIO_CMD_20,

	INPUT_FUNCTION_RADIO_CMD_21,
	INPUT_FUNCTION_RADIO_CMD_22,
	INPUT_FUNCTION_RADIO_CMD_23,
	INPUT_FUNCTION_RADIO_CMD_24,
	INPUT_FUNCTION_RADIO_CMD_25,
	INPUT_FUNCTION_RADIO_CMD_26,
	INPUT_FUNCTION_RADIO_CMD_27,
	INPUT_FUNCTION_RADIO_CMD_28,
	INPUT_FUNCTION_RADIO_CMD_29,
	INPUT_FUNCTION_RADIO_CMD_30,

	INPUT_FUNCTION_TEAM_INFO_TOGGLE,
	INPUT_FUNCTION_BATTLE_INFO_TOGGLE,
	INPUT_FUNCTION_SERVER_INFO_TOGGLE,

	//INPUT_FUNCTION_VERBOSE_HELP_PAGE_UP,
	//INPUT_FUNCTION_VERBOSE_HELP_PAGE_DOWN,

	INPUT_FUNCTION_PROFILE_ENTER_CHILD0,
	INPUT_FUNCTION_PROFILE_ENTER_CHILD1,
	INPUT_FUNCTION_PROFILE_ENTER_CHILD2,
	INPUT_FUNCTION_PROFILE_ENTER_CHILD3,
	INPUT_FUNCTION_PROFILE_ENTER_CHILD4,
	INPUT_FUNCTION_PROFILE_ENTER_CHILD5,
	INPUT_FUNCTION_PROFILE_ENTER_CHILD6,
	INPUT_FUNCTION_PROFILE_ENTER_CHILD7,
	INPUT_FUNCTION_PROFILE_ENTER_CHILD8,
	INPUT_FUNCTION_PROFILE_ENTER_CHILD9,
	INPUT_FUNCTION_PROFILE_ENTER_PARENT,
	INPUT_FUNCTION_PROFILE_RESET,

	INPUT_FUNCTION_COUNT

} InputFunction;
#ifdef TTINIT_EXPORTS
#define TTINIT_EXPORT __declspec(dllexport)
#else
#define TTINIT_EXPORT __declspec(dllimport)
#endif
class Input
{
public:
	enum {
		QUEUE_MAX		= 20,
		FIRST_SLIDER			= 0x7000,
		SLIDER_MOUSE_LEFT	= FIRST_SLIDER,
		SLIDER_MOUSE_RIGHT,
		SLIDER_MOUSE_UP,
		SLIDER_MOUSE_DOWN,
		SLIDER_MOUSE_WHEEL_FORWARD,
		SLIDER_MOUSE_WHEEL_BACKWARD,
		SLIDER_JOYSTICK_LEFT,
		SLIDER_JOYSTICK_RIGHT,
		SLIDER_JOYSTICK_UP,
		SLIDER_JOYSTICK_DOWN,
		LAST_SLIDER_PLUS_ONE,
		NUM_SLIDERS				= LAST_SLIDER_PLUS_ONE - FIRST_SLIDER
	};
	TTINIT_EXPORT static bool Is_Button_Down(int keyCode);
	TTINIT_EXPORT static float Get_Value(int, int, float);
	static	void	Load_Configuration (const char *filename);
	static	void	Save_Configuration (const char *filename);
	TTINIT_EXPORT static	void	Update( void );
	static	void	Flush( void );
	static	void	Get_Translated_Key_Name (int dik_id, WideStringClass &name);
	static	short	Get_Key( const char *name );
	static	const char * Get_Key_Name (short key_id);
	static REF_DECL1(MenuMode, bool);
	static REF_DECL1(ConsoleMode, bool);
	static	bool	Get_State( InputFunction function )		{ return (MenuMode || ConsoleMode) ? false : Peek_State (function); }
	static	bool	Peek_State( InputFunction function )	{ return (FunctionValue[ function ] > 0.5f); }
	TTINIT_EXPORT static int Get_Primary_Key_For_Function (int function_id);
	static REF_ARR_DECL1(FunctionValue, float, INPUT_FUNCTION_COUNT);
private:
	static	void	Save_Accelerated_Keys (INIClass *input_ini);
	static	void	Save_Misc_Settings (INIClass	*input_ini);
	static	void	Free_Mappings( void );
	static	void	Load_Accelerated_Keys (INIClass *input_ini);
	static	void	Load_Misc_Settings (INIClass	*input_ini);
	static	void	Set_Mouse_Sensitivity( float mouse_sensitivity );
	static	void	Load_Accelerated_Key (INIClass *input_ini, const char *section_name);
	static	short	Get_Function( const char *name );
	static REF_DECL1(UsingDirectInput, bool);
	static	void	Update_Sliders( void );
	static	float	Sliders[ NUM_SLIDERS ];
	static REF_ARR_DECL1(FunctionPrimaryKeys, int, INPUT_FUNCTION_COUNT);
	static REF_ARR_DECL1(FunctionSecondaryKeys, int, INPUT_FUNCTION_COUNT);
	static REF_DECL1(DamageIndicatorsEnabled,bool);
};

#endif